---
- hosts: localhost
  become: true
  vars:
   server_name: 
  tasks:
   - name: Install Nginx
     apt: 
      pkg: nginx
      state: installed
      update_cache: true
     notify:
      - start nginx
   - name: Latest Ngix Version
     apt: 
      name: nginx 
      state: latest
   - name: Start Nginx
     service:
      name: nginx
      state: started
