---
- hosts: localhost
  become: yes
  vars:
   server_name: 
   tasks:
   - name: Install Nginx
     apt: pkg=ngix state=installed update_cache=true
   
     notify:
      - start nginx
   
   - name: Latest Nginx Version
     apt: name=nginx state=latest
   
   - name: Start Nginx
     service:
      name: nginx
      state: restarted
      handlers:
        - name: Start Nginx
          service: name=nginx state=started
