---
- hosts: localhost
  become: true
  tasks:

  - name: Start service http, if not running
    service:
      name: httpd
      state: started

  - name: Stop service httpd, if running
    service:
      name: httpd
      state: stopped

  - name: Restart service httpd, in all cases
    service:
      name: httpd
      state: restarted

  - name: Reload service httpd, in all cases
    service:
      name: httpd
      state: reloaded

  - name: Enable service httpd, and not touch the running state
    service:
      name: httpd
      enabled: yes

  - name: Start service foo, based on running process /usr/bin/foo
    service:
      name: foo
      pattern: /usr/bin/foo
      state: started

  - name: Restart network service for interface eth0
    service:
      name: network
      state: restarted
      args: etih0
